update: graceful shutdown for recording sidecar container in K8s
Signed-off-by: Viet Nguyen Duc <nguyenducviet4496@gmail.com>

diff --git a/tests/charts/ci/local-pvc.yaml b/tests/charts/ci/local-pvc.yaml
--- a/tests/charts/ci/local-pvc.yaml
+++ b/tests/charts/ci/local-pvc.yaml
@@ -21,6 +21,30 @@ spec:
               value: "seluser|selenium.dev"
             - name: MAX_PORT
               value: "21005"
+            - name: TINI_SUBREAPER
+              value: "true"
+          command:
+            - /bin/sh
+            - -c
+            - |
+              max_attempts=5;
+              attempt_num=1;
+              while [ $attempt_num -le $max_attempts ];
+              do
+                output=$(eval "/sbin/tini -- /bin/start_vsftpd.sh");
+                status=$?;
+                if [ $status -eq 0 ]; then
+                  break;
+                else
+                  echo "Attempt $attempt_num failed! Trying again in 3 seconds...";
+                  attempt_num=$((attempt_num+1));
+                  sleep 3;
+                fi
+              done;
+              if [ $attempt_num -gt $max_attempts ]; then
+                echo "All attempts to start vsftpd failed.";
+                exit 1;
+              fi
           volumeMounts:
             - mountPath: /ftp/seluser
               name: ftp-upload
diff --git a/tests/docker-compose-v3-test-node-docker.yaml b/tests/docker-compose-v3-test-node-docker.yaml
--- a/tests/docker-compose-v3-test-node-docker.yaml
+++ b/tests/docker-compose-v3-test-node-docker.yaml
@@ -15,6 +15,7 @@ services:
       - "prod.domain.com:${HOST_IP}"
     depends_on:
       - selenium-hub
+      - ftp_server
     environment:
       - SE_NODE_DOCKER_CONFIG_FILENAME=docker.toml
       - SE_EVENT_BUS_HOST=selenium-hub
@@ -55,8 +56,31 @@ services:
     environment:
       - USERS=seluser|selenium.dev
       - MAX_PORT=21010
+      - TINI_SUBREAPER=true
     volumes:
       - ./videos/upload:/ftp/seluser
+    entrypoint: >
+      /bin/sh -c '
+      max_attempts=5;
+      attempt_num=1;
+      while [ $attempt_num -le $max_attempts ];
+      do
+        output=$(eval "/sbin/tini -- /bin/start_vsftpd.sh");
+        status=$?;
+        if [ $status -eq 0 ]; then
+          break;
+        else
+          echo "Attempt $attempt_num failed! Trying again in 3 seconds...";
+          attempt_num=$((attempt_num+1));
+          sleep 3;
+        fi
+      done;
+      if [ $attempt_num -gt $max_attempts ]; then
+        echo "All attempts to start vsftpd failed.";
+        exit 1;
+      fi
+      '
+    restart: unless-stopped
     stop_grace_period: 30s
 
   tests:
diff --git a/tests/docker-compose-v3-test-standalone-docker.yaml b/tests/docker-compose-v3-test-standalone-docker.yaml
--- a/tests/docker-compose-v3-test-standalone-docker.yaml
+++ b/tests/docker-compose-v3-test-standalone-docker.yaml
@@ -2,6 +2,8 @@ version: "3"
 services:
   standalone-docker:
     image: ${NAMESPACE}/standalone-docker:${TAG}
+    depends_on:
+      - ftp_server
     volumes:
       - ./videos:/opt/selenium/assets
       - ./videos/config.toml:/opt/selenium/config.toml
@@ -40,8 +42,31 @@ services:
     environment:
       - USERS=seluser|selenium.dev
       - MAX_PORT=21010
+      - TINI_SUBREAPER=true
     volumes:
       - ./videos/upload:/ftp/seluser
+    entrypoint: >
+      /bin/sh -c '
+      max_attempts=5;
+      attempt_num=1;
+      while [ $attempt_num -le $max_attempts ];
+      do
+        output=$(eval "/sbin/tini -- /bin/start_vsftpd.sh");
+        status=$?;
+        if [ $status -eq 0 ]; then
+          break;
+        else
+          echo "Attempt $attempt_num failed! Trying again in 3 seconds...";
+          attempt_num=$((attempt_num+1));
+          sleep 3;
+        fi
+      done;
+      if [ $attempt_num -gt $max_attempts ]; then
+        echo "All attempts to start vsftpd failed.";
+        exit 1;
+      fi
+      '
+    restart: unless-stopped
     stop_grace_period: 30s
 
   tests:
diff --git a/tests/docker-compose-v3-test-standalone.yml b/tests/docker-compose-v3-test-standalone.yml
--- a/tests/docker-compose-v3-test-standalone.yml
+++ b/tests/docker-compose-v3-test-standalone.yml
@@ -9,6 +9,8 @@ services:
     user: ${UID}
     shm_size: 2gb
     container_name: standalone
+    depends_on:
+      - browser_video
     environment:
       - SE_NODE_MAX_SESSIONS=1
       - SE_NODE_OVERRIDE_MAX_SESSIONS=true
@@ -19,12 +21,16 @@ services:
       - SE_SUB_PATH=${SUB_PATH}
     ports:
       - "4444:4444"
+    healthcheck:
+      test: "/opt/bin/check-grid.sh --host 0.0.0.0 --port 4444"
+      interval: 15s
+      timeout: 30s
+      retries: 5
 
   browser_video:
     image: selenium/video:${VIDEO_TAG}
     user: ${UID}
     depends_on:
-      - standalone
       - ftp_server
     environment:
       - SE_VIDEO_RECORD_STANDALONE=true
@@ -52,8 +58,31 @@ services:
     environment:
       - USERS=seluser|selenium.dev
       - MAX_PORT=21010
+      - TINI_SUBREAPER=true
     volumes:
       - ./videos/upload:/ftp/seluser
+    entrypoint: >
+      /bin/sh -c '
+      max_attempts=5;
+      attempt_num=1;
+      while [ $attempt_num -le $max_attempts ];
+      do
+        output=$(eval "/sbin/tini -- /bin/start_vsftpd.sh");
+        status=$?;
+        if [ $status -eq 0 ]; then
+          break;
+        else
+          echo "Attempt $attempt_num failed! Trying again in 3 seconds...";
+          attempt_num=$((attempt_num+1));
+          sleep 3;
+        fi
+      done;
+      if [ $attempt_num -gt $max_attempts ]; then
+        echo "All attempts to start vsftpd failed.";
+        exit 1;
+      fi
+      '
+    restart: unless-stopped
     stop_grace_period: 30s
 
   tests:
diff --git a/tests/docker-compose-v3-test-video.yml b/tests/docker-compose-v3-test-video.yml
--- a/tests/docker-compose-v3-test-video.yml
+++ b/tests/docker-compose-v3-test-video.yml
@@ -9,6 +9,7 @@ services:
     shm_size: 2gb
     depends_on:
       - selenium-hub
+      - browser_video
     environment:
       - SE_EVENT_BUS_HOST=selenium-hub
       - SE_EVENT_BUS_PUBLISH_PORT=4442
@@ -21,7 +22,7 @@ services:
     image: selenium/video:${VIDEO_TAG}
     user: ${UID}
     depends_on:
-      - browser
+      - ftp_server
     environment:
       - SE_NODE_GRID_URL=http://selenium-hub:4444
       - DISPLAY_CONTAINER_NAME=browser
@@ -45,8 +46,31 @@ services:
     environment:
       - USERS=seluser|selenium.dev
       - MAX_PORT=21010
+      - TINI_SUBREAPER=true
     volumes:
       - ./videos/upload:/ftp/seluser
+    entrypoint: >
+      /bin/sh -c '
+      max_attempts=5;
+      attempt_num=1;
+      while [ $attempt_num -le $max_attempts ];
+      do
+        output=$(eval "/sbin/tini -- /bin/start_vsftpd.sh");
+        status=$?;
+        if [ $status -eq 0 ]; then
+          break;
+        else
+          echo "Attempt $attempt_num failed! Trying again in 3 seconds...";
+          attempt_num=$((attempt_num+1));
+          sleep 3;
+        fi
+      done;
+      if [ $attempt_num -gt $max_attempts ]; then
+        echo "All attempts to start vsftpd failed.";
+        exit 1;
+      fi
+      '
+    restart: unless-stopped
     stop_grace_period: 30s
 
   selenium-hub:
@@ -57,6 +81,11 @@ services:
       - "4442:4442"
       - "4443:4443"
       - "4444:4444"
+    healthcheck:
+      test: "/opt/bin/check-grid.sh --host 0.0.0.0 --port 4444"
+      interval: 15s
+      timeout: 30s
+      retries: 5
 
   tests:
     image: docker-selenium-tests:latest
@@ -65,6 +94,7 @@ services:
       dockerfile: ./Dockerfile
     depends_on:
       - selenium-hub
+      - browser
     environment:
       - RUN_IN_DOCKER_COMPOSE=true
       - SELENIUM_GRID_HOST=selenium-hub
